import type { Metadata } from 'next';
import './globals.css';
import SessionProvider from '@/providers/session-provider';
import { Toaster } from '@/components/ui/sonner';
import Theme from '@/providers/theme-provider';
import { primaryFont } from '@/config/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className={`${primaryFont.className}`}>
            <SessionProvider>
                <body className={''}>
                    <Theme
                        attribute='class'
                        defaultTheme='light'
                        disableTransitionOnChange
                    >
                        {children}
                    </Theme>
                    <Toaster />
                </body>
            </SessionProvider>
        </html>
    );
}
