import {
    ABeeZee,
    Abel,
    Abhaya_Libre,
    Abril_Fatface,
    Aclonica,
    Acme,
    Actor,
    Adamina,
    Advent_Pro,
    Aguafina_Script,
    Akaya_Kanadaka,
    Akaya_Telivigala,
    Akronim,
    Aladin,
    Alata,
    Alatsi,
    Aldrich,
    Alef,
    Alegreya,
    Alegreya_SC,
    Alegreya_Sans,
    Alegreya_Sans_SC,
    Aleo,
    Alex_Brush,
    Alfa_Slab_One,
    Alice,
    Alike,
    Alike_Angular,
    Allan,
    Allerta,
    Allerta_Stencil,
    Allison,
    Allura,
    Almarai,
    Almendra,
    Almendra_Display,
    Almendra_SC,
    Alumni_Sans,
    Amarante,
    Amaranth,
    Amatic_SC,
    Amethysta,
    Amiko,
    Amiri,
    Amita,
    Anaheim,
    Andada_Pro,
    Andika,
    Angkor,
    Annie_Use_Your_Telescope,
    Anonymous_Pro,
    Antic,
    Antic_Didone,
    Antic_Slab,
    Anton,
    Antonio,
    Arapey,
    Arbutus,
    Arbutus_Slab,
    Architects_Daughter,
    Archivo,
    Archivo_Black,
    Archivo_Narrow,
    Are_You_Serious,
    Aref_Ruqaa,
    Arimo,
    Arizonia,
    Armata,
    Arsenal,
    Artifika,
    Arvo,
    Arya,
    Asap,
    Asap_Condensed,
    Asar,
    Asset,
    Assistant,
    Astloch,
    Asul,
    Athiti,
    Atkinson_Hyperlegible,
    Atma,
    Atomic_Age,
    Aubrey,
    Audiowide,
    Autour_One,
    Average,
    Average_Sans,
    Averia_Gruesa_Libre,
    Averia_Libre,
    Averia_Sans_Libre,
    Averia_Serif_Libre,
    Azeret_Mono,
    B612,
    B612_Mono,
    Bad_Script,
    Bahiana,
    Bahianita,
    Bai_Jamjuree,
    Ballet,
    Baloo_2,
    Baloo_Bhai_2,
    Baloo_Bhaina_2,
    Baloo_Chettan_2,
    Baloo_Da_2,
    Baloo_Paaji_2,
    Baloo_Tamma_2,
    Baloo_Tammudu_2,
    Baloo_Thambi_2,
    Balsamiq_Sans,
    Balthazar,
    Bangers,
    Barlow,
    Barlow_Condensed,
    Barlow_Semi_Condensed,
    Barriecito,
    Barrio,
    Basic,
    Baskervville,
    Battambang,
    Baumans,
    Bayon,
    Be_Vietnam_Pro,
    Bebas_Neue,
    Belgrano,
    Bellefair,
    Belleza,
    Bellota,
    Bellota_Text,
    BenchNine,
    Benne,
    Bentham,
    Berkshire_Swash,
    Besley,
    Beth_Ellen,
    Bevan,
    Big_Shoulders_Display,
    Big_Shoulders_Inline_Display,
    Big_Shoulders_Inline_Text,
    Big_Shoulders_Stencil_Display,
    Big_Shoulders_Stencil_Text,
    Big_Shoulders_Text,
    Bigelow_Rules,
    Bigshot_One,
    Bilbo,
    Bilbo_Swash_Caps,
    BioRhyme,
    BioRhyme_Expanded,
    Birthstone,
    Birthstone_Bounce,
    Biryani,
    Bitter,
    Black_And_White_Picture,
    Black_Han_Sans,
    Black_Ops_One,
    Blinker,
    Bodoni_Moda,
    Bokor,
    Bona_Nova,
    Bonbon,
    Bonheur_Royale,
    Boogaloo,
    Bowlby_One,
    Bowlby_One_SC,
    Brawler,
    Bree_Serif,
    Brygada_1918,
    Bubblegum_Sans,
    Bubbler_One,
    Buda,
    Buenard,
    Bungee,
    Bungee_Hairline,
    Bungee_Inline,
    Bungee_Outline,
    Bungee_Shade,
    Butcherman,
    Butterfly_Kids,
    Cabin,
    Cabin_Condensed,
    Cabin_Sketch,
    Caesar_Dressing,
    Cagliostro,
    Cairo,
    Caladea,
    Calistoga,
    Calligraffitti,
    Cambay,
    Cambo,
    Candal,
    Cantarell,
    Cantata_One,
    Cantora_One,
    Capriola,
    Caramel,
    Carattere,
    Cardo,
    Carme,
    Carrois_Gothic,
    Carrois_Gothic_SC,
    Carter_One,
    Castoro,
    Catamaran,
    Caudex,
    Caveat,
    Caveat_Brush,
    Cedarville_Cursive,
    Ceviche_One,
    Chakra_Petch,
    Changa,
    Changa_One,
    Chango,
    Charm,
    Charmonman,
    Chathura,
    Chau_Philomene_One,
    Chela_One,
    Chelsea_Market,
    Chenla,
    Cherish,
    Cherry_Cream_Soda,
    Cherry_Swash,
    Chewy,
    Chicle,
    Chilanka,
    Chivo,
    Chonburi,
    Cinzel,
    Cinzel_Decorative,
    Clicker_Script,
    Coda,
    Codystar,
    Coiny,
    Combo,
    Comfortaa,
    Comic_Neue,
    Coming_Soon,
    Commissioner,
    Concert_One,
    Condiment,
    Content,
    Contrail_One,
    Convergence,
    Cookie,
    Copse,
    Corben,
    Cormorant,
    Cormorant_Garamond,
    Cormorant_Infant,
    Cormorant_SC,
    Cormorant_Unicase,
    Cormorant_Upright,
    Courgette,
    Courier_Prime,
    Cousine,
    Coustard,
    Covered_By_Your_Grace,
    Crafty_Girls,
    Creepster,
    Crete_Round,
    Crimson_Pro,
    Crimson_Text,
    Croissant_One,
    Crushed,
    Cuprum,
    Cute_Font,
    Cutive,
    Cutive_Mono,
    DM_Mono,
    DM_Sans,
    DM_Serif_Display,
    DM_Serif_Text,
    Damion,
    Dancing_Script,
    Dangrek,
    Darker_Grotesque,
    David_Libre,
    Dawning_of_a_New_Day,
    Days_One,
    Dekko,
    Dela_Gothic_One,
    Delius,
    Delius_Swash_Caps,
    Delius_Unicase,
    Della_Respira,
    Denk_One,
    Devonshire,
    Dhurjati,
    Didact_Gothic,
    Diplomata,
    Diplomata_SC,
    Do_Hyeon,
    Dokdo,
    Domine,
    Donegal_One,
    Doppio_One,
    Dorsa,
    Dosis,
    DotGothic16,
    Dr_Sugiyama,
    Duru_Sans,
    Dynalight,
    EB_Garamond,
    Eagle_Lake,
    East_Sea_Dokdo,
    Eater,
    Economica,
    Eczar,
    El_Messiri,
    Electrolize,
    Elsie,
    Elsie_Swash_Caps,
    Emblema_One,
    Emilys_Candy,
    Encode_Sans,
    Encode_Sans_Condensed,
    Encode_Sans_Expanded,
    Encode_Sans_SC,
    Encode_Sans_Semi_Condensed,
    Encode_Sans_Semi_Expanded,
    Engagement,
    Englebert,
    Enriqueta,
    Ephesis,
    Epilogue,
    Erica_One,
    Esteban,
    Euphoria_Script,
    Ewert,
    Exo,
    Exo_2,
    Expletus_Sans,
    Explora,
    Fahkwang,
    Fanwood_Text,
    Farro,
    Farsan,
    Fascinate,
    Fascinate_Inline,
    Faster_One,
    Fasthand,
    Fauna_One,
    Faustina,
    Federant,
    Federo,
    Felipa,
    Fenix,
    Festive,
    Finger_Paint,
    Fira_Code,
    Fira_Mono,
    Fira_Sans,
    Fira_Sans_Condensed,
    Fira_Sans_Extra_Condensed,
    Fjalla_One,
    Fjord_One,
    Flamenco,
    Flavors,
    Fleur_De_Leah,
    Fondamento,
    Fontdiner_Swanky,
    Forum,
    Francois_One,
    Frank_Ruhl_Libre,
    Fraunces,
    Freckle_Face,
    Fredericka_the_Great,
    Freehand,
    Fresca,
    Frijole,
    Fruktur,
    Fugaz_One,
    Fuggles,
    GFS_Didot,
    GFS_Neohellenic,
    Gabriela,
    Gaegu,
    Gafata,
    Galada,
    Galdeano,
    Galindo,
    Gamja_Flower,
    Gayathri,
    Gelasio,
    Gemunu_Libre,
    Geo,
    Georama,
    Geostar,
    Geostar_Fill,
    Germania_One,
    Gideon_Roman,
    Gidugu,
    Gilda_Display,
    Girassol,
    Give_You_Glory,
    Glass_Antiqua,
    Glegoo,
    Gloria_Hallelujah,
    Glory,
    Gluten,
    Goblin_One,
    Gochi_Hand,
    Goldman,
    Gorditas,
    Gothic_A1,
    Gotu,
    Goudy_Bookletter_1911,
    Gowun_Batang,
    Gowun_Dodum,
    Graduate,
    Grand_Hotel,
    Grandstander,
    Gravitas_One,
    Great_Vibes,
    Grechen_Fuemen,
    Grenze,
    Grenze_Gotisch,
    Grey_Qo,
    Griffy,
    Gruppo,
    Gudea,
    Gugi,
    Gupter,
    Gurajada,
    Habibi,
    Hachi_Maru_Pop,
    Hahmlet,
    Halant,
    Hammersmith_One,
    Hanalei,
    Hanalei_Fill,
    Handlee,
    Hanuman,
    Happy_Monkey,
    Harmattan,
    Headland_One,
    Heebo,
    Henny_Penny,
    Hepta_Slab,
    Herr_Von_Muellerhoff,
    Hi_Melody,
    Hina_Mincho,
    Hind,
    Hind_Guntur,
    Hind_Madurai,
    Hind_Siliguri,
    Hind_Vadodara,
    Holtwood_One_SC,
    Homemade_Apple,
    Homenaje,
    IBM_Plex_Mono,
    IBM_Plex_Sans,
    IBM_Plex_Sans_Arabic,
    IBM_Plex_Sans_Condensed,
    IBM_Plex_Sans_Devanagari,
    IBM_Plex_Sans_Hebrew,
    IBM_Plex_Sans_KR,
    IBM_Plex_Sans_Thai,
    IBM_Plex_Sans_Thai_Looped,
    IBM_Plex_Serif,
    IM_Fell_DW_Pica,
    IM_Fell_DW_Pica_SC,
    IM_Fell_Double_Pica,
    IM_Fell_Double_Pica_SC,
    IM_Fell_English,
    IM_Fell_English_SC,
    IM_Fell_French_Canon,
    IM_Fell_French_Canon_SC,
    IM_Fell_Great_Primer,
    IM_Fell_Great_Primer_SC,
    Ibarra_Real_Nova,
    Iceberg,
    Iceland,
    Imbue,
    Imprima,
    Inconsolata,
    Inder,
    Indie_Flower,
    Inika,
    Inknut_Antiqua,
    Inria_Sans,
    Inria_Serif,
    Inter,
    Irish_Grover,
    Istok_Web,
    Italiana,
    Italianno,
    Itim,
    Jacques_Francois,
    Jacques_Francois_Shadow,
    Jaldi,
    JetBrains_Mono,
    Jim_Nightshade,
    Jockey_One,
    Jolly_Lodger,
    Jomhuria,
    Jomolhari,
    Josefin_Sans,
    Josefin_Slab,
    Jost,
    Joti_One,
    Jua,
    Judson,
    Julee,
    Julius_Sans_One,
    Junge,
    Jura,
    Just_Another_Hand,
    Just_Me_Again_Down_Here,
    K2D,
    Kadwa,
    Kaisei_Decol,
    Kaisei_HarunoUmi,
    Kaisei_Opti,
    Kaisei_Tokumin,
    Kalam,
    Kameron,
    Kanit,
    Karantina,
    Karla,
    Karma,
    Katibeh,
    Kaushan_Script,
    Kavivanar,
    Kavoon,
    Keania_One,
    Kelly_Slab,
    Kenia,
    Khand,
    Khmer,
    Khula,
    Kirang_Haerang,
    Kite_One,
    Kiwi_Maru,
    Klee_One,
    Knewave,
    KoHo,
    Kodchasan,
    Koh_Santepheap,
    Kosugi,
    Kosugi_Maru,
    Kotta_One,
    Koulen,
    Kranky,
    Kreon,
    Kristi,
    Krona_One,
    Krub,
    Kufam,
    Kulim_Park,
    Kumar_One,
    Kumar_One_Outline,
    Kumbh_Sans,
    Kurale,
    La_Belle_Aurore,
    Lacquer,
    Laila,
    Lakki_Reddy,
    Lalezar,
    Lancelot,
    Langar,
    Lateef,
    Lato,
    League_Script,
    Leckerli_One,
    Ledger,
    Lekton,
    Lemon,
    Lemonada,
    Lexend,
    Lexend_Deca,
    Lexend_Exa,
    Lexend_Giga,
    Lexend_Mega,
    Lexend_Peta,
    Lexend_Tera,
    Lexend_Zetta,
    Libre_Barcode_128,
    Libre_Barcode_128_Text,
    Libre_Barcode_39,
    Libre_Barcode_39_Extended,
    Libre_Barcode_39_Extended_Text,
    Libre_Barcode_39_Text,
    Libre_Barcode_EAN13_Text,
    Libre_Baskerville,
    Libre_Caslon_Display,
    Libre_Caslon_Text,
    Libre_Franklin,
    Life_Savers,
    Lilita_One,
    Lily_Script_One,
    Limelight,
    Linden_Hill,
    Literata,
    Liu_Jian_Mao_Cao,
    Livvic,
    Lobster,
    Lobster_Two,
    Londrina_Outline,
    Londrina_Shadow,
    Londrina_Sketch,
    Londrina_Solid,
    Long_Cang,
    Lora,
    Love_Ya_Like_A_Sister,
    Loved_by_the_King,
    Lovers_Quarrel,
    Luckiest_Guy,
    Lusitana,
    Lustria,
    M_PLUS_1p,
    M_PLUS_Rounded_1c,
    Ma_Shan_Zheng,
    Macondo,
    Macondo_Swash_Caps,
    Mada,
    Magra,
    Maiden_Orange,
    Maitree,
    Major_Mono_Display,
    Mako,
    Mali,
    Mallanna,
    Mandali,
    Manjari,
    Manrope,
    Mansalva,
    Manuale,
    Marcellus,
    Marcellus_SC,
    Marck_Script,
    Margarine,
    Markazi_Text,
    Marko_One,
    Marmelad,
    Martel,
    Martel_Sans,
    Marvel,
    Mate,
    Mate_SC,
    Maven_Pro,
    McLaren,
    Meddon,
    MedievalSharp,
    Medula_One,
    Meera_Inimai,
    Megrim,
    Meie_Script,
    Merienda,
    Merriweather,
    Merriweather_Sans,
    Metal,
    Metal_Mania,
    Metamorphous,
    Metrophobic,
    Michroma,
    Milonga,
    Miltonian,
    Miltonian_Tattoo,
    Mina,
    Miniver,
    Miriam_Libre,
    Mirza,
    Miss_Fajardose,
    Mitr,
    Modak,
    Modern_Antiqua,
    Mogra,
    Molengo,
    Molle,
    Monda,
    Monofett,
    Monoton,
    Monsieur_La_Doulaise,
    Montaga,
    MonteCarlo,
    Montez,
    Montserrat,
    Montserrat_Alternates,
    Montserrat_Subrayada,
    Moul,
    Moulpali,
    Mountains_of_Christmas,
    Mouse_Memoirs,
    Mr_Bedfort,
    Mr_Dafoe,
    Mr_De_Haviland,
    Mrs_Saint_Delafield,
    Mrs_Sheppards,
    Mukta,
    Mukta_Mahee,
    Mukta_Malar,
    Mukta_Vaani,
    Mulish,
    MuseoModerno,
    Mystery_Quest,
    NTR,
    Nanum_Brush_Script,
    Nanum_Gothic,
    Nanum_Gothic_Coding,
    Nanum_Myeongjo,
    Nanum_Pen_Script,
    Nerko_One,
    Neucha,
    Neuton,
    New_Rocker,
    New_Tegomin,
    News_Cycle,
    Newsreader,
    Niconne,
    Niramit,
    Nixie_One,
    Nobile,
    Nokora,
    Norican,
    Nosifer,
    Notable,
    Nothing_You_Could_Do,
    Noticia_Text,
    Noto_Kufi_Arabic,
    Noto_Music,
    Noto_Naskh_Arabic,
    Noto_Nastaliq_Urdu,
    Noto_Rashi_Hebrew,
    Noto_Sans,
    Noto_Sans_Adlam,
    Noto_Sans_Adlam_Unjoined,
    Noto_Sans_Anatolian_Hieroglyphs,
    Noto_Sans_Arabic,
    Noto_Sans_Armenian,
    Noto_Sans_Avestan,
    Noto_Sans_Balinese,
    Noto_Sans_Bamum,
    Noto_Sans_Bassa_Vah,
    Noto_Sans_Batak,
    Noto_Sans_Bengali,
    Noto_Sans_Bhaiksuki,
    Noto_Sans_Brahmi,
    Noto_Sans_Buginese,
    Noto_Sans_Buhid,
    Noto_Sans_Canadian_Aboriginal,
    Noto_Sans_Carian,
    Noto_Sans_Caucasian_Albanian,
    Noto_Sans_Chakma,
    Noto_Sans_Cham,
    Noto_Sans_Cherokee,
    Noto_Sans_Coptic,
    Noto_Sans_Cuneiform,
    Noto_Sans_Cypriot,
    Noto_Sans_Deseret,
    Noto_Sans_Devanagari,
    Noto_Sans_Display,
    Noto_Sans_Duployan,
    Noto_Sans_Egyptian_Hieroglyphs,
    Noto_Sans_Elbasan,
    Noto_Sans_Elymaic,
    Noto_Sans_Georgian,
    Noto_Sans_Glagolitic,
    Noto_Sans_Gothic,
    Noto_Sans_Grantha,
    Noto_Sans_Gujarati,
    Noto_Sans_Gunjala_Gondi,
    Noto_Sans_Gurmukhi,
    Noto_Sans_HK,
    Noto_Sans_Hanifi_Rohingya,
    Noto_Sans_Hanunoo,
    Noto_Sans_Hatran,
    Noto_Sans_Hebrew,
    Noto_Sans_Imperial_Aramaic,
    Noto_Sans_Indic_Siyaq_Numbers,
    Noto_Sans_Inscriptional_Pahlavi,
    Noto_Sans_Inscriptional_Parthian,
    Noto_Sans_JP,
    Noto_Sans_Javanese,
    Noto_Sans_KR,
    Noto_Sans_Kaithi,
    Noto_Sans_Kannada,
    Noto_Sans_Kayah_Li,
    Noto_Sans_Kharoshthi,
    Noto_Sans_Khmer,
    Noto_Sans_Khojki,
    Noto_Sans_Khudawadi,
    Noto_Sans_Lao,
    Noto_Sans_Lepcha,
    Noto_Sans_Limbu,
    Noto_Sans_Linear_A,
    Noto_Sans_Linear_B,
    Noto_Sans_Lisu,
    Noto_Sans_Lycian,
    Noto_Sans_Lydian,
    Noto_Sans_Mahajani,
    Noto_Sans_Malayalam,
    Noto_Sans_Mandaic,
    Noto_Sans_Manichaean,
    Noto_Sans_Marchen,
    Noto_Sans_Masaram_Gondi,
    Noto_Sans_Math,
    Noto_Sans_Mayan_Numerals,
    Noto_Sans_Medefaidrin,
    Noto_Sans_Meroitic,
    Noto_Sans_Miao,
    Noto_Sans_Modi,
    Noto_Sans_Mongolian,
    Noto_Sans_Mono,
    Noto_Sans_Mro,
    Noto_Sans_Multani,
    Noto_Sans_Myanmar,
    Noto_Sans_Nabataean,
    Noto_Sans_New_Tai_Lue,
    Noto_Sans_Newa,
    Noto_Sans_Nushu,
    Noto_Sans_Ogham,
    Noto_Sans_Ol_Chiki,
    Noto_Sans_Old_Hungarian,
    Noto_Sans_Old_Italic,
    Noto_Sans_Old_North_Arabian,
    Noto_Sans_Old_Permic,
    Noto_Sans_Old_Persian,
    Noto_Sans_Old_Sogdian,
    Noto_Sans_Old_South_Arabian,
    Noto_Sans_Old_Turkic,
    Noto_Sans_Oriya,
    Noto_Sans_Osage,
    Noto_Sans_Osmanya,
    Noto_Sans_Pahawh_Hmong,
    Noto_Sans_Palmyrene,
    Noto_Sans_Pau_Cin_Hau,
    Noto_Sans_Phags_Pa,
    Noto_Sans_Phoenician,
    Noto_Sans_Psalter_Pahlavi,
    Noto_Sans_Rejang,
    Noto_Sans_Runic,
    Noto_Sans_SC,
    Noto_Sans_Samaritan,
    Noto_Sans_Saurashtra,
    Noto_Sans_Sharada,
    Noto_Sans_Shavian,
    Noto_Sans_Siddham,
    Noto_Sans_Sinhala,
    Noto_Sans_Sogdian,
    Noto_Sans_Sora_Sompeng,
    Noto_Sans_Soyombo,
    Noto_Sans_Sundanese,
    Noto_Sans_Syloti_Nagri,
    Noto_Sans_Symbols,
    Noto_Sans_Symbols_2,
    Noto_Sans_Syriac,
    Noto_Sans_TC,
    Noto_Sans_Tagalog,
    Noto_Sans_Tagbanwa,
    Noto_Sans_Tai_Le,
    Noto_Sans_Tai_Tham,
    Noto_Sans_Tai_Viet,
    Noto_Sans_Takri,
    Noto_Sans_Tamil,
    Noto_Sans_Tamil_Supplement,
    Noto_Sans_Telugu,
    Noto_Sans_Thaana,
    Noto_Sans_Thai,
    Noto_Sans_Thai_Looped,
    Noto_Sans_Tifinagh,
    Noto_Sans_Tirhuta,
    Noto_Sans_Ugaritic,
    Noto_Sans_Vai,
    Noto_Sans_Wancho,
    Noto_Sans_Warang_Citi,
    Noto_Sans_Yi,
    Noto_Sans_Zanabazar_Square,
    Noto_Serif,
    Noto_Serif_Ahom,
    Noto_Serif_Armenian,
    Noto_Serif_Balinese,
    Noto_Serif_Bengali,
    Noto_Serif_Devanagari,
    Noto_Serif_Display,
    Noto_Serif_Dogra,
    Noto_Serif_Ethiopic,
    Noto_Serif_Georgian,
    Noto_Serif_Grantha,
    Noto_Serif_Gujarati,
    Noto_Serif_Gurmukhi,
    Noto_Serif_Hebrew,
    Noto_Serif_JP,
    Noto_Serif_KR,
    Noto_Serif_Kannada,
    Noto_Serif_Khmer,
    Noto_Serif_Lao,
    Noto_Serif_Malayalam,
    Noto_Serif_Myanmar,
    Noto_Serif_SC,
    Noto_Serif_Sinhala,
    Noto_Serif_TC,
    Noto_Serif_Tamil,
    Noto_Serif_Tangut,
    Noto_Serif_Telugu,
    Noto_Serif_Thai,
    Noto_Serif_Tibetan,
    Noto_Serif_Yezidi,
    Noto_Traditional_Nushu,
    Nova_Cut,
    Nova_Flat,
    Nova_Mono,
    Nova_Oval,
    Nova_Round,
    Nova_Script,
    Nova_Slim,
    Nova_Square,
    Numans,
    Nunito,
    Nunito_Sans,
    Odibee_Sans,
    Odor_Mean_Chey,
    Offside,
    Oi,
    Old_Standard_TT,
    Oldenburg,
    Oleo_Script,
    Oleo_Script_Swash_Caps,
    Open_Sans,
    Oranienbaum,
    Orbitron,
    Oregano,
    Orelega_One,
    Orienta,
    Original_Surfer,
    Oswald,
    Over_the_Rainbow,
    Overlock,
    Overlock_SC,
    Overpass,
    Overpass_Mono,
    Ovo,
    Oxanium,
    Oxygen,
    Oxygen_Mono,
    PT_Mono,
    PT_Sans,
    PT_Sans_Caption,
    PT_Sans_Narrow,
    PT_Serif,
    PT_Serif_Caption,
    Pacifico,
    Padauk,
    Palanquin,
    Palanquin_Dark,
    Palette_Mosaic,
    Pangolin,
    Paprika,
    Parisienne,
    Passero_One,
    Passion_One,
    Pathway_Gothic_One,
    Patrick_Hand,
    Patrick_Hand_SC,
    Pattaya,
    Patua_One,
    Pavanam,
    Paytone_One,
    Peddana,
    Peralta,
    Permanent_Marker,
    Petit_Formal_Script,
    Petrona,
    Philosopher,
    Piazzolla,
    Piedra,
    Pinyon_Script,
    Pirata_One,
    Plaster,
    Play,
    Playball,
    Playfair_Display,
    Playfair_Display_SC,
    Podkova,
    Poiret_One,
    Poller_One,
    Poly,
    Pompiere,
    Pontano_Sans,
    Poor_Story,
    Poppins,
    Port_Lligat_Sans,
    Port_Lligat_Slab,
    Potta_One,
    Pragati_Narrow,
    Prata,
    Preahvihear,
    Press_Start_2P,
    Pridi,
    Princess_Sofia,
    Prociono,
    Prompt,
    Prosto_One,
    Proza_Libre,
    Public_Sans,
    Puritan,
    Purple_Purse,
    Qahiri,
    Quando,
    Quantico,
    Quattrocento,
    Quattrocento_Sans,
    Questrial,
    Quicksand,
    Quintessential,
    Qwigley,
    Racing_Sans_One,
    Radley,
    Rajdhani,
    Rakkas,
    Raleway,
    Raleway_Dots,
    Ramabhadra,
    Ramaraja,
    Rambla,
    Rammetto_One,
    Rampart_One,
    Ranchers,
    Rancho,
    Ranga,
    Rasa,
    Rationale,
    Ravi_Prakash,
    Recursive,
    Red_Hat_Display,
    Red_Hat_Text,
    Red_Rose,
    Redressed,
    Reem_Kufi,
    Reenie_Beanie,
    Reggae_One,
    Revalia,
    Rhodium_Libre,
    Ribeye,
    Ribeye_Marrow,
    Righteous,
    Risque,
    Roboto,
    Roboto_Condensed,
    Roboto_Mono,
    Roboto_Slab,
    Rochester,
    Rock_Salt,
    RocknRoll_One,
    Rokkitt,
    Romanesco,
    Ropa_Sans,
    Rosario,
    Rosarivo,
    Rouge_Script,
    Rowdies,
    Rozha_One,
    Rubik,
    Rubik_Beastly,
    Rubik_Mono_One,
    Ruda,
    Rufina,
    Ruge_Boogie,
    Ruluko,
    Rum_Raisin,
    Ruslan_Display,
    Russo_One,
    Ruthie,
    Rye,
    STIX_Two_Text,
    Sacramento,
    Sahitya,
    Sail,
    Saira,
    Saira_Condensed,
    Saira_Extra_Condensed,
    Saira_Semi_Condensed,
    Saira_Stencil_One,
    Salsa,
    Sanchez,
    Sancreek,
    Sansita,
    Sansita_Swashed,
    Sarabun,
    Sarala,
    Sarina,
    Sarpanch,
    Satisfy,
    Sawarabi_Gothic,
    Sawarabi_Mincho,
    Scada,
    Scheherazade_New,
    Schoolbell,
    Scope_One,
    Seaweed_Script,
    Secular_One,
    Sedgwick_Ave,
    Sedgwick_Ave_Display,
    Sen,
    Sevillana,
    Seymour_One,
    Shadows_Into_Light,
    Shadows_Into_Light_Two,
    Shanti,
    Share,
    Share_Tech,
    Share_Tech_Mono,
    Shippori_Mincho,
    Shippori_Mincho_B1,
    Shojumaru,
    Short_Stack,
    Shrikhand,
    Siemreap,
    Sigmar_One,
    Signika,
    Signika_Negative,
    Simonetta,
    Single_Day,
    Sintony,
    Sirin_Stencil,
    Six_Caps,
    Skranji,
    Slabo_13px,
    Slabo_27px,
    Slackey,
    Smokum,
    Smythe,
    Sniglet,
    Snippet,
    Snowburst_One,
    Sofadi_One,
    Sofia,
    Solway,
    Song_Myung,
    Sonsie_One,
    Sora,
    Sorts_Mill_Goudy,
    Source_Code_Pro,
    Space_Grotesk,
    Space_Mono,
    Special_Elite,
    Spectral,
    Spectral_SC,
    Spicy_Rice,
    Spinnaker,
    Spirax,
    Squada_One,
    Sree_Krushnadevaraya,
    Sriracha,
    Srisakdi,
    Staatliches,
    Stalemate,
    Stalinist_One,
    Stardos_Stencil,
    Stick,
    Stick_No_Bills,
    Stint_Ultra_Condensed,
    Stint_Ultra_Expanded,
    Stoke,
    Strait,
    Style_Script,
    Stylish,
    Sue_Ellen_Francisco,
    Suez_One,
    Sulphur_Point,
    Sumana,
    Sunflower,
    Sunshiney,
    Supermercado_One,
    Sura,
    Suranna,
    Suravaram,
    Suwannaphum,
    Swanky_and_Moo_Moo,
    Syncopate,
    Syne,
    Syne_Mono,
    Syne_Tactile,
    Tajawal,
    Tangerine,
    Taprom,
    Tauri,
    Taviraj,
    Teko,
    Telex,
    Tenali_Ramakrishna,
    Tenor_Sans,
    Text_Me_One,
    Texturina,
    Thasadith,
    The_Girl_Next_Door,
    Tienne,
    Tillana,
    Timmana,
    Tinos,
    Titan_One,
    Titillium_Web,
    Tomorrow,
    Tourney,
    Trade_Winds,
    Train_One,
    Trirong,
    Trispace,
    Trocchi,
    Trochut,
    Truculenta,
    Trykker,
    Tulpen_One,
    Turret_Road,
    Ubuntu,
    Ubuntu_Condensed,
    Ubuntu_Mono,
    Uchen,
    Ultra,
    Uncial_Antiqua,
    Underdog,
    Unica_One,
    UnifrakturCook,
    UnifrakturMaguntia,
    Unkempt,
    Unlock,
    Unna,
    Urbanist,
    VT323,
    Vampiro_One,
    Varela,
    Varela_Round,
    Varta,
    Vast_Shadow,
    Vesper_Libre,
    Viaoda_Libre,
    Vibes,
    Vibur,
    Vidaloka,
    Viga,
    Voces,
    Volkhov,
    Vollkorn,
    Vollkorn_SC,
    Voltaire,
    Waiting_for_the_Sunrise,
    Wallpoet,
    Walter_Turncoat,
    Warnes,
    Wellfleet,
    Wendy_One,
    WindSong,
    Wire_One,
    Work_Sans,
    Xanh_Mono,
    Yaldevi,
    Yanone_Kaffeesatz,
    Yantramanav,
    Yatra_One,
    Yellowtail,
    Yeon_Sung,
    Yeseva_One,
    Yesteryear,
    Yomogi,
    Yrsa,
    Yusei_Magic,
    ZCOOL_KuaiLe,
    ZCOOL_QingKe_HuangYou,
    ZCOOL_XiaoWei,
    Zen_Antique,
    Zen_Antique_Soft,
    Zen_Dots,
    Zen_Kaku_Gothic_Antique,
    Zen_Kaku_Gothic_New,
    Zen_Kurenaido,
    Zen_Loop,
    Zen_Maru_Gothic,
    Zen_Old_Mincho,
    Zen_Tokyo_Zoo,
    Zeyada,
    Zhi_Mang_Xing,
    Zilla_Slab,
    Zilla_Slab_Highlight,
} from 'next/font/google';

const FONTS = [
    'ABeeZee',
    'Abel',
    'Abhaya Libre',
    'Abril Fatface',
    'Aclonica',
    'Acme',
    'Actor',
    'Adamina',
    'Advent Pro',
    'Aguafina Script',
    'Akaya Kanadaka',
    'Akaya Telivigala',
    'Akronim',
    'Aladin',
    'Alata',
    'Alatsi',
    'Aldrich',
    'Alef',
    'Alegreya',
    'Alegreya SC',
    'Alegreya Sans',
    'Alegreya Sans SC',
    'Aleo',
    'Alex Brush',
    'Alfa Slab One',
    'Alice',
    'Alike',
    'Alike Angular',
    'Allan',
    'Allerta',
    'Allerta Stencil',
    'Allison',
    'Allura',
    'Almarai',
    'Almendra',
    'Almendra Display',
    'Almendra SC',
    'Alumni Sans',
    'Amarante',
    'Amaranth',
    'Amatic SC',
    'Amethysta',
    'Amiko',
    'Amiri',
    'Amita',
    'Anaheim',
    'Andada Pro',
    'Andika',
    'Andika New Basic',
    'Angkor',
    'Annie Use Your Telescope',
    'Anonymous Pro',
    'Antic',
    'Antic Didone',
    'Antic Slab',
    'Anton',
    'Antonio',
    'Arapey',
    'Arbutus',
    'Arbutus Slab',
    'Architects Daughter',
    'Archivo',
    'Archivo Black',
    'Archivo Narrow',
    'Are You Serious',
    'Aref Ruqaa',
    'Arima Madurai',
    'Arimo',
    'Arizonia',
    'Armata',
    'Arsenal',
    'Artifika',
    'Arvo',
    'Arya',
    'Asap',
    'Asap Condensed',
    'Asar',
    'Asset',
    'Assistant',
    'Astloch',
    'Asul',
    'Athiti',
    'Atkinson Hyperlegible',
    'Atma',
    'Atomic Age',
    'Aubrey',
    'Audiowide',
    'Autour One',
    'Average',
    'Average Sans',
    'Averia Gruesa Libre',
    'Averia Libre',
    'Averia Sans Libre',
    'Averia Serif Libre',
    'Azeret Mono',
    'B612',
    'B612 Mono',
    'Bad Script',
    'Bahiana',
    'Bahianita',
    'Bai Jamjuree',
    'Ballet',
    'Baloo 2',
    'Baloo Bhai 2',
    'Baloo Bhaina 2',
    'Baloo Chettan 2',
    'Baloo Da 2',
    'Baloo Paaji 2',
    'Baloo Tamma 2',
    'Baloo Tammudu 2',
    'Baloo Thambi 2',
    'Balsamiq Sans',
    'Balthazar',
    'Bangers',
    'Barlow',
    'Barlow Condensed',
    'Barlow Semi Condensed',
    'Barriecito',
    'Barrio',
    'Basic',
    'Baskervville',
    'Battambang',
    'Baumans',
    'Bayon',
    'Be Vietnam',
    'Be Vietnam Pro',
    'Bebas Neue',
    'Belgrano',
    'Bellefair',
    'Belleza',
    'Bellota',
    'Bellota Text',
    'BenchNine',
    'Benne',
    'Bentham',
    'Berkshire Swash',
    'Besley',
    'Beth Ellen',
    'Bevan',
    'Big Shoulders Display',
    'Big Shoulders Inline Display',
    'Big Shoulders Inline Text',
    'Big Shoulders Stencil Display',
    'Big Shoulders Stencil Text',
    'Big Shoulders Text',
    'Bigelow Rules',
    'Bigshot One',
    'Bilbo',
    'Bilbo Swash Caps',
    'BioRhyme',
    'BioRhyme Expanded',
    'Birthstone',
    'Birthstone Bounce',
    'Biryani',
    'Bitter',
    'Black And White Picture',
    'Black Han Sans',
    'Black Ops One',
    'Blinker',
    'Bodoni Moda',
    'Bokor',
    'Bona Nova',
    'Bonbon',
    'Bonheur Royale',
    'Boogaloo',
    'Bowlby One',
    'Bowlby One SC',
    'Brawler',
    'Bree Serif',
    'Brygada 1918',
    'Bubblegum Sans',
    'Bubbler One',
    'Buda',
    'Buenard',
    'Bungee',
    'Bungee Hairline',
    'Bungee Inline',
    'Bungee Outline',
    'Bungee Shade',
    'Butcherman',
    'Butterfly Kids',
    'Cabin',
    'Cabin Condensed',
    'Cabin Sketch',
    'Caesar Dressing',
    'Cagliostro',
    'Cairo',
    'Caladea',
    'Calistoga',
    'Calligraffitti',
    'Cambay',
    'Cambo',
    'Candal',
    'Cantarell',
    'Cantata One',
    'Cantora One',
    'Capriola',
    'Caramel',
    'Carattere',
    'Cardo',
    'Carme',
    'Carrois Gothic',
    'Carrois Gothic SC',
    'Carter One',
    'Castoro',
    'Catamaran',
    'Caudex',
    'Caveat',
    'Caveat Brush',
    'Cedarville Cursive',
    'Ceviche One',
    'Chakra Petch',
    'Changa',
    'Changa One',
    'Chango',
    'Charm',
    'Charmonman',
    'Chathura',
    'Chau Philomene One',
    'Chela One',
    'Chelsea Market',
    'Chenla',
    'Cherish',
    'Cherry Cream Soda',
    'Cherry Swash',
    'Chewy',
    'Chicle',
    'Chilanka',
    'Chivo',
    'Chonburi',
    'Cinzel',
    'Cinzel Decorative',
    'Clicker Script',
    'Coda',
    'Coda Caption',
    'Codystar',
    'Coiny',
    'Combo',
    'Comfortaa',
    'Comic Neue',
    'Coming Soon',
    'Commissioner',
    'Concert One',
    'Condiment',
    'Content',
    'Contrail One',
    'Convergence',
    'Cookie',
    'Copse',
    'Corben',
    'Cormorant',
    'Cormorant Garamond',
    'Cormorant Infant',
    'Cormorant SC',
    'Cormorant Unicase',
    'Cormorant Upright',
    'Courgette',
    'Courier Prime',
    'Cousine',
    'Coustard',
    'Covered By Your Grace',
    'Crafty Girls',
    'Creepster',
    'Crete Round',
    'Crimson Pro',
    'Crimson Text',
    'Croissant One',
    'Crushed',
    'Cuprum',
    'Cute Font',
    'Cutive',
    'Cutive Mono',
    'DM Mono',
    'DM Sans',
    'DM Serif Display',
    'DM Serif Text',
    'Damion',
    'Dancing Script',
    'Dangrek',
    'Darker Grotesque',
    'David Libre',
    'Dawning of a New Day',
    'Days One',
    'Dekko',
    'Dela Gothic One',
    'Delius',
    'Delius Swash Caps',
    'Delius Unicase',
    'Della Respira',
    'Denk One',
    'Devonshire',
    'Dhurjati',
    'Didact Gothic',
    'Diplomata',
    'Diplomata SC',
    'Do Hyeon',
    'Dokdo',
    'Domine',
    'Donegal One',
    'Doppio One',
    'Dorsa',
    'Dosis',
    'DotGothic16',
    'Dr Sugiyama',
    'Duru Sans',
    'Dynalight',
    'EB Garamond',
    'Eagle Lake',
    'East Sea Dokdo',
    'Eater',
    'Economica',
    'Eczar',
    'El Messiri',
    'Electrolize',
    'Elsie',
    'Elsie Swash Caps',
    'Emblema One',
    'Emilys Candy',
    'Encode Sans',
    'Encode Sans Condensed',
    'Encode Sans Expanded',
    'Encode Sans SC',
    'Encode Sans Semi Condensed',
    'Encode Sans Semi Expanded',
    'Engagement',
    'Englebert',
    'Enriqueta',
    'Ephesis',
    'Epilogue',
    'Erica One',
    'Esteban',
    'Euphoria Script',
    'Ewert',
    'Exo',
    'Exo 2',
    'Expletus Sans',
    'Explora',
    'Fahkwang',
    'Fanwood Text',
    'Farro',
    'Farsan',
    'Fascinate',
    'Fascinate Inline',
    'Faster One',
    'Fasthand',
    'Fauna One',
    'Faustina',
    'Federant',
    'Federo',
    'Felipa',
    'Fenix',
    'Festive',
    'Finger Paint',
    'Fira Code',
    'Fira Mono',
    'Fira Sans',
    'Fira Sans Condensed',
    'Fira Sans Extra Condensed',
    'Fjalla One',
    'Fjord One',
    'Flamenco',
    'Flavors',
    'Fleur De Leah',
    'Fondamento',
    'Fontdiner Swanky',
    'Forum',
    'Francois One',
    'Frank Ruhl Libre',
    'Fraunces',
    'Freckle Face',
    'Fredericka the Great',
    'Fredoka One',
    'Freehand',
    'Fresca',
    'Frijole',
    'Fruktur',
    'Fugaz One',
    'Fuggles',
    'GFS Didot',
    'GFS Neohellenic',
    'Gabriela',
    'Gaegu',
    'Gafata',
    'Galada',
    'Galdeano',
    'Galindo',
    'Gamja Flower',
    'Gayathri',
    'Gelasio',
    'Gemunu Libre',
    'Gentium Basic',
    'Gentium Book Basic',
    'Geo',
    'Georama',
    'Geostar',
    'Geostar Fill',
    'Germania One',
    'Gideon Roman',
    'Gidugu',
    'Gilda Display',
    'Girassol',
    'Give You Glory',
    'Glass Antiqua',
    'Glegoo',
    'Gloria Hallelujah',
    'Glory',
    'Gluten',
    'Goblin One',
    'Gochi Hand',
    'Goldman',
    'Gorditas',
    'Gothic A1',
    'Gotu',
    'Goudy Bookletter 1911',
    'Gowun Batang',
    'Gowun Dodum',
    'Graduate',
    'Grand Hotel',
    'Grandstander',
    'Gravitas One',
    'Great Vibes',
    'Grechen Fuemen',
    'Grenze',
    'Grenze Gotisch',
    'Grey Qo',
    'Griffy',
    'Gruppo',
    'Gudea',
    'Gugi',
    'Gupter',
    'Gurajada',
    'Habibi',
    'Hachi Maru Pop',
    'Hahmlet',
    'Halant',
    'Hammersmith One',
    'Hanalei',
    'Hanalei Fill',
    'Handlee',
    'Hanuman',
    'Happy Monkey',
    'Harmattan',
    'Headland One',
    'Heebo',
    'Henny Penny',
    'Hepta Slab',
    'Herr Von Muellerhoff',
    'Hi Melody',
    'Hina Mincho',
    'Hind',
    'Hind Guntur',
    'Hind Madurai',
    'Hind Siliguri',
    'Hind Vadodara',
    'Holtwood One SC',
    'Homemade Apple',
    'Homenaje',
    'IBM Plex Mono',
    'IBM Plex Sans',
    'IBM Plex Sans Arabic',
    'IBM Plex Sans Condensed',
    'IBM Plex Sans Devanagari',
    'IBM Plex Sans Hebrew',
    'IBM Plex Sans KR',
    'IBM Plex Sans Thai',
    'IBM Plex Sans Thai Looped',
    'IBM Plex Serif',
    'IM Fell DW Pica',
    'IM Fell DW Pica SC',
    'IM Fell Double Pica',
    'IM Fell Double Pica SC',
    'IM Fell English',
    'IM Fell English SC',
    'IM Fell French Canon',
    'IM Fell French Canon SC',
    'IM Fell Great Primer',
    'IM Fell Great Primer SC',
    'Ibarra Real Nova',
    'Iceberg',
    'Iceland',
    'Imbue',
    'Imprima',
    'Inconsolata',
    'Inder',
    'Indie Flower',
    'Inika',
    'Inknut Antiqua',
    'Inria Sans',
    'Inria Serif',
    'Inter',
    'Irish Grover',
    'Istok Web',
    'Italiana',
    'Italianno',
    'Itim',
    'Jacques Francois',
    'Jacques Francois Shadow',
    'Jaldi',
    'JetBrains Mono',
    'Jim Nightshade',
    'Jockey One',
    'Jolly Lodger',
    'Jomhuria',
    'Jomolhari',
    'Josefin Sans',
    'Josefin Slab',
    'Jost',
    'Joti One',
    'Jua',
    'Judson',
    'Julee',
    'Julius Sans One',
    'Junge',
    'Jura',
    'Just Another Hand',
    'Just Me Again Down Here',
    'K2D',
    'Kadwa',
    'Kaisei Decol',
    'Kaisei HarunoUmi',
    'Kaisei Opti',
    'Kaisei Tokumin',
    'Kalam',
    'Kameron',
    'Kanit',
    'Kantumruy',
    'Karantina',
    'Karla',
    'Karma',
    'Katibeh',
    'Kaushan Script',
    'Kavivanar',
    'Kavoon',
    'Kdam Thmor',
    'Keania One',
    'Kelly Slab',
    'Kenia',
    'Khand',
    'Khmer',
    'Khula',
    'Kirang Haerang',
    'Kite One',
    'Kiwi Maru',
    'Klee One',
    'Knewave',
    'KoHo',
    'Kodchasan',
    'Koh Santepheap',
    'Kosugi',
    'Kosugi Maru',
    'Kotta One',
    'Koulen',
    'Kranky',
    'Kreon',
    'Kristi',
    'Krona One',
    'Krub',
    'Kufam',
    'Kulim Park',
    'Kumar One',
    'Kumar One Outline',
    'Kumbh Sans',
    'Kurale',
    'La Belle Aurore',
    'Lacquer',
    'Laila',
    'Lakki Reddy',
    'Lalezar',
    'Lancelot',
    'Langar',
    'Lateef',
    'Lato',
    'League Script',
    'Leckerli One',
    'Ledger',
    'Lekton',
    'Lemon',
    'Lemonada',
    'Lexend',
    'Lexend Deca',
    'Lexend Exa',
    'Lexend Giga',
    'Lexend Mega',
    'Lexend Peta',
    'Lexend Tera',
    'Lexend Zetta',
    'Libre Barcode 128',
    'Libre Barcode 128 Text',
    'Libre Barcode 39',
    'Libre Barcode 39 Extended',
    'Libre Barcode 39 Extended Text',
    'Libre Barcode 39 Text',
    'Libre Barcode EAN13 Text',
    'Libre Baskerville',
    'Libre Caslon Display',
    'Libre Caslon Text',
    'Libre Franklin',
    'Life Savers',
    'Lilita One',
    'Lily Script One',
    'Limelight',
    'Linden Hill',
    'Literata',
    'Liu Jian Mao Cao',
    'Livvic',
    'Lobster',
    'Lobster Two',
    'Londrina Outline',
    'Londrina Shadow',
    'Londrina Sketch',
    'Londrina Solid',
    'Long Cang',
    'Lora',
    'Love Ya Like A Sister',
    'Loved by the King',
    'Lovers Quarrel',
    'Luckiest Guy',
    'Lusitana',
    'Lustria',
    'M PLUS 1p',
    'M PLUS Rounded 1c',
    'Ma Shan Zheng',
    'Macondo',
    'Macondo Swash Caps',
    'Mada',
    'Magra',
    'Maiden Orange',
    'Maitree',
    'Major Mono Display',
    'Mako',
    'Mali',
    'Mallanna',
    'Mandali',
    'Manjari',
    'Manrope',
    'Mansalva',
    'Manuale',
    'Marcellus',
    'Marcellus SC',
    'Marck Script',
    'Margarine',
    'Markazi Text',
    'Marko One',
    'Marmelad',
    'Martel',
    'Martel Sans',
    'Marvel',
    'Mate',
    'Mate SC',
    'Material Icons',
    'Maven Pro',
    'McLaren',
    'Meddon',
    'MedievalSharp',
    'Medula One',
    'Meera Inimai',
    'Megrim',
    'Meie Script',
    'Merienda',
    'Merienda One',
    'Merriweather',
    'Merriweather Sans',
    'Metal',
    'Metal Mania',
    'Metamorphous',
    'Metrophobic',
    'Michroma',
    'Milonga',
    'Miltonian',
    'Miltonian Tattoo',
    'Mina',
    'Miniver',
    'Miriam Libre',
    'Mirza',
    'Miss Fajardose',
    'Mitr',
    'Modak',
    'Modern Antiqua',
    'Mogra',
    'Molengo',
    'Molle',
    'Monda',
    'Monofett',
    'Monoton',
    'Monsieur La Doulaise',
    'Montaga',
    'MonteCarlo',
    'Montez',
    'Montserrat',
    'Montserrat Alternates',
    'Montserrat Subrayada',
    'Moul',
    'Moulpali',
    'Mountains of Christmas',
    'Mouse Memoirs',
    'Mr Bedfort',
    'Mr Dafoe',
    'Mr De Haviland',
    'Mrs Saint Delafield',
    'Mrs Sheppards',
    'Mukta',
    'Mukta Mahee',
    'Mukta Malar',
    'Mukta Vaani',
    'Mulish',
    'MuseoModerno',
    'Mystery Quest',
    'NTR',
    'Nanum Brush Script',
    'Nanum Gothic',
    'Nanum Gothic Coding',
    'Nanum Myeongjo',
    'Nanum Pen Script',
    'Nerko One',
    'Neucha',
    'Neuton',
    'New Rocker',
    'New Tegomin',
    'News Cycle',
    'Newsreader',
    'Niconne',
    'Niramit',
    'Nixie One',
    'Nobile',
    'Nokora',
    'Norican',
    'Nosifer',
    'Notable',
    'Nothing You Could Do',
    'Noticia Text',
    'Noto Kufi Arabic',
    'Noto Music',
    'Noto Naskh Arabic',
    'Noto Nastaliq Urdu',
    'Noto Rashi Hebrew',
    'Noto Sans',
    'Noto Sans Adlam',
    'Noto Sans Adlam Unjoined',
    'Noto Sans Anatolian Hieroglyphs',
    'Noto Sans Arabic',
    'Noto Sans Armenian',
    'Noto Sans Avestan',
    'Noto Sans Balinese',
    'Noto Sans Bamum',
    'Noto Sans Bassa Vah',
    'Noto Sans Batak',
    'Noto Sans Bengali',
    'Noto Sans Bhaiksuki',
    'Noto Sans Brahmi',
    'Noto Sans Buginese',
    'Noto Sans Buhid',
    'Noto Sans Canadian Aboriginal',
    'Noto Sans Carian',
    'Noto Sans Caucasian Albanian',
    'Noto Sans Chakma',
    'Noto Sans Cham',
    'Noto Sans Cherokee',
    'Noto Sans Coptic',
    'Noto Sans Cuneiform',
    'Noto Sans Cypriot',
    'Noto Sans Deseret',
    'Noto Sans Devanagari',
    'Noto Sans Display',
    'Noto Sans Duployan',
    'Noto Sans Egyptian Hieroglyphs',
    'Noto Sans Elbasan',
    'Noto Sans Elymaic',
    'Noto Sans Georgian',
    'Noto Sans Glagolitic',
    'Noto Sans Gothic',
    'Noto Sans Grantha',
    'Noto Sans Gujarati',
    'Noto Sans Gunjala Gondi',
    'Noto Sans Gurmukhi',
    'Noto Sans HK',
    'Noto Sans Hanifi Rohingya',
    'Noto Sans Hanunoo',
    'Noto Sans Hatran',
    'Noto Sans Hebrew',
    'Noto Sans Imperial Aramaic',
    'Noto Sans Indic Siyaq Numbers',
    'Noto Sans Inscriptional Pahlavi',
    'Noto Sans Inscriptional Parthian',
    'Noto Sans JP',
    'Noto Sans Javanese',
    'Noto Sans KR',
    'Noto Sans Kaithi',
    'Noto Sans Kannada',
    'Noto Sans Kayah Li',
    'Noto Sans Kharoshthi',
    'Noto Sans Khmer',
    'Noto Sans Khojki',
    'Noto Sans Khudawadi',
    'Noto Sans Lao',
    'Noto Sans Lepcha',
    'Noto Sans Limbu',
    'Noto Sans Linear A',
    'Noto Sans Linear B',
    'Noto Sans Lisu',
    'Noto Sans Lycian',
    'Noto Sans Lydian',
    'Noto Sans Mahajani',
    'Noto Sans Malayalam',
    'Noto Sans Mandaic',
    'Noto Sans Manichaean',
    'Noto Sans Marchen',
    'Noto Sans Masaram Gondi',
    'Noto Sans Math',
    'Noto Sans Mayan Numerals',
    'Noto Sans Medefaidrin',
    'Noto Sans Meroitic',
    'Noto Sans Miao',
    'Noto Sans Modi',
    'Noto Sans Mongolian',
    'Noto Sans Mono',
    'Noto Sans Mro',
    'Noto Sans Multani',
    'Noto Sans Myanmar',
    'Noto Sans N Ko',
    'Noto Sans Nabataean',
    'Noto Sans New Tai Lue',
    'Noto Sans Newa',
    'Noto Sans Nushu',
    'Noto Sans Ogham',
    'Noto Sans Ol Chiki',
    'Noto Sans Old Hungarian',
    'Noto Sans Old Italic',
    'Noto Sans Old North Arabian',
    'Noto Sans Old Permic',
    'Noto Sans Old Persian',
    'Noto Sans Old Sogdian',
    'Noto Sans Old South Arabian',
    'Noto Sans Old Turkic',
    'Noto Sans Oriya',
    'Noto Sans Osage',
    'Noto Sans Osmanya',
    'Noto Sans Pahawh Hmong',
    'Noto Sans Palmyrene',
    'Noto Sans Pau Cin Hau',
    'Noto Sans Phags Pa',
    'Noto Sans Phoenician',
    'Noto Sans Psalter Pahlavi',
    'Noto Sans Rejang',
    'Noto Sans Runic',
    'Noto Sans SC',
    'Noto Sans Samaritan',
    'Noto Sans Saurashtra',
    'Noto Sans Sharada',
    'Noto Sans Shavian',
    'Noto Sans Siddham',
    'Noto Sans Sinhala',
    'Noto Sans Sogdian',
    'Noto Sans Sora Sompeng',
    'Noto Sans Soyombo',
    'Noto Sans Sundanese',
    'Noto Sans Syloti Nagri',
    'Noto Sans Symbols',
    'Noto Sans Symbols 2',
    'Noto Sans Syriac',
    'Noto Sans TC',
    'Noto Sans Tagalog',
    'Noto Sans Tagbanwa',
    'Noto Sans Tai Le',
    'Noto Sans Tai Tham',
    'Noto Sans Tai Viet',
    'Noto Sans Takri',
    'Noto Sans Tamil',
    'Noto Sans Tamil Supplement',
    'Noto Sans Telugu',
    'Noto Sans Thaana',
    'Noto Sans Thai',
    'Noto Sans Thai Looped',
    'Noto Sans Tifinagh',
    'Noto Sans Tirhuta',
    'Noto Sans Ugaritic',
    'Noto Sans Vai',
    'Noto Sans Wancho',
    'Noto Sans Warang Citi',
    'Noto Sans Yi',
    'Noto Sans Zanabazar Square',
    'Noto Serif',
    'Noto Serif Ahom',
    'Noto Serif Armenian',
    'Noto Serif Balinese',
    'Noto Serif Bengali',
    'Noto Serif Devanagari',
    'Noto Serif Display',
    'Noto Serif Dogra',
    'Noto Serif Ethiopic',
    'Noto Serif Georgian',
    'Noto Serif Grantha',
    'Noto Serif Gujarati',
    'Noto Serif Gurmukhi',
    'Noto Serif Hebrew',
    'Noto Serif JP',
    'Noto Serif KR',
    'Noto Serif Kannada',
    'Noto Serif Khmer',
    'Noto Serif Lao',
    'Noto Serif Malayalam',
    'Noto Serif Myanmar',
    'Noto Serif Nyiakeng Puachue Hmong',
    'Noto Serif SC',
    'Noto Serif Sinhala',
    'Noto Serif TC',
    'Noto Serif Tamil',
    'Noto Serif Tangut',
    'Noto Serif Telugu',
    'Noto Serif Thai',
    'Noto Serif Tibetan',
    'Noto Serif Yezidi',
    'Noto Traditional Nushu',
    'Nova Cut',
    'Nova Flat',
    'Nova Mono',
    'Nova Oval',
    'Nova Round',
    'Nova Script',
    'Nova Slim',
    'Nova Square',
    'Numans',
    'Nunito',
    'Nunito Sans',
    'Odibee Sans',
    'Odor Mean Chey',
    'Offside',
    'Oi',
    'Old Standard TT',
    'Oldenburg',
    'Oleo Script',
    'Oleo Script Swash Caps',
    'Open Sans',
    'Open Sans Condensed',
    'Oranienbaum',
    'Orbitron',
    'Oregano',
    'Orelega One',
    'Orienta',
    'Original Surfer',
    'Oswald',
    'Otomanopee One',
    'Over the Rainbow',
    'Overlock',
    'Overlock SC',
    'Overpass',
    'Overpass Mono',
    'Ovo',
    'Oxanium',
    'Oxygen',
    'Oxygen Mono',
    'PT Mono',
    'PT Sans',
    'PT Sans Caption',
    'PT Sans Narrow',
    'PT Serif',
    'PT Serif Caption',
    'Pacifico',
    'Padauk',
    'Palanquin',
    'Palanquin Dark',
    'Palette Mosaic',
    'Pangolin',
    'Paprika',
    'Parisienne',
    'Passero One',
    'Passion One',
    'Pathway Gothic One',
    'Patrick Hand',
    'Patrick Hand SC',
    'Pattaya',
    'Patua One',
    'Pavanam',
    'Paytone One',
    'Peddana',
    'Peralta',
    'Permanent Marker',
    'Petit Formal Script',
    'Petrona',
    'Philosopher',
    'Piazzolla',
    'Piedra',
    'Pinyon Script',
    'Pirata One',
    'Plaster',
    'Play',
    'Playball',
    'Playfair Display',
    'Playfair Display SC',
    'Podkova',
    'Poiret One',
    'Poller One',
    'Poly',
    'Pompiere',
    'Pontano Sans',
    'Poor Story',
    'Poppins',
    'Port Lligat Sans',
    'Port Lligat Slab',
    'Potta One',
    'Pragati Narrow',
    'Prata',
    'Preahvihear',
    'Press Start 2P',
    'Pridi',
    'Princess Sofia',
    'Prociono',
    'Prompt',
    'Prosto One',
    'Proza Libre',
    'Public Sans',
    'Puritan',
    'Purple Purse',
    'Qahiri',
    'Quando',
    'Quantico',
    'Quattrocento',
    'Quattrocento Sans',
    'Questrial',
    'Quicksand',
    'Quintessential',
    'Qwigley',
    'Racing Sans One',
    'Radley',
    'Rajdhani',
    'Rakkas',
    'Raleway',
    'Raleway Dots',
    'Ramabhadra',
    'Ramaraja',
    'Rambla',
    'Rammetto One',
    'Rampart One',
    'Ranchers',
    'Rancho',
    'Ranga',
    'Rasa',
    'Rationale',
    'Ravi Prakash',
    'Recursive',
    'Red Hat Display',
    'Red Hat Text',
    'Red Rose',
    'Redressed',
    'Reem Kufi',
    'Reenie Beanie',
    'Reggae One',
    'Revalia',
    'Rhodium Libre',
    'Ribeye',
    'Ribeye Marrow',
    'Righteous',
    'Risque',
    'Roboto',
    'Roboto Condensed',
    'Roboto Mono',
    'Roboto Slab',
    'Rochester',
    'Rock Salt',
    'RocknRoll One',
    'Rokkitt',
    'Romanesco',
    'Ropa Sans',
    'Rosario',
    'Rosarivo',
    'Rouge Script',
    'Rowdies',
    'Rozha One',
    'Rubik',
    'Rubik Beastly',
    'Rubik Mono One',
    'Ruda',
    'Rufina',
    'Ruge Boogie',
    'Ruluko',
    'Rum Raisin',
    'Ruslan Display',
    'Russo One',
    'Ruthie',
    'Rye',
    'STIX Two Text',
    'Sacramento',
    'Sahitya',
    'Sail',
    'Saira',
    'Saira Condensed',
    'Saira Extra Condensed',
    'Saira Semi Condensed',
    'Saira Stencil One',
    'Salsa',
    'Sanchez',
    'Sancreek',
    'Sansita',
    'Sansita Swashed',
    'Sarabun',
    'Sarala',
    'Sarina',
    'Sarpanch',
    'Satisfy',
    'Sawarabi Gothic',
    'Sawarabi Mincho',
    'Scada',
    'Scheherazade',
    'Scheherazade New',
    'Schoolbell',
    'Scope One',
    'Seaweed Script',
    'Secular One',
    'Sedgwick Ave',
    'Sedgwick Ave Display',
    'Sen',
    'Sevillana',
    'Seymour One',
    'Shadows Into Light',
    'Shadows Into Light Two',
    'Shanti',
    'Share',
    'Share Tech',
    'Share Tech Mono',
    'Shippori Mincho',
    'Shippori Mincho B1',
    'Shojumaru',
    'Short Stack',
    'Shrikhand',
    'Siemreap',
    'Sigmar One',
    'Signika',
    'Signika Negative',
    'Simonetta',
    'Single Day',
    'Sintony',
    'Sirin Stencil',
    'Six Caps',
    'Skranji',
    'Slabo 13px',
    'Slabo 27px',
    'Slackey',
    'Smokum',
    'Smythe',
    'Sniglet',
    'Snippet',
    'Snowburst One',
    'Sofadi One',
    'Sofia',
    'Solway',
    'Song Myung',
    'Sonsie One',
    'Sora',
    'Sorts Mill Goudy',
    'Source Code Pro',
    'Source Sans Pro',
    'Source Serif Pro',
    'Space Grotesk',
    'Space Mono',
    'Spartan',
    'Special Elite',
    'Spectral',
    'Spectral SC',
    'Spicy Rice',
    'Spinnaker',
    'Spirax',
    'Squada One',
    'Sree Krushnadevaraya',
    'Sriracha',
    'Srisakdi',
    'Staatliches',
    'Stalemate',
    'Stalinist One',
    'Stardos Stencil',
    'Stick',
    'Stick No Bills',
    'Stint Ultra Condensed',
    'Stint Ultra Expanded',
    'Stoke',
    'Strait',
    'Style Script',
    'Stylish',
    'Sue Ellen Francisco',
    'Suez One',
    'Sulphur Point',
    'Sumana',
    'Sunflower',
    'Sunshiney',
    'Supermercado One',
    'Sura',
    'Suranna',
    'Suravaram',
    'Suwannaphum',
    'Swanky and Moo Moo',
    'Syncopate',
    'Syne',
    'Syne Mono',
    'Syne Tactile',
    'Tajawal',
    'Tangerine',
    'Taprom',
    'Tauri',
    'Taviraj',
    'Teko',
    'Telex',
    'Tenali Ramakrishna',
    'Tenor Sans',
    'Text Me One',
    'Texturina',
    'Thasadith',
    'The Girl Next Door',
    'Tienne',
    'Tillana',
    'Timmana',
    'Tinos',
    'Titan One',
    'Titillium Web',
    'Tomorrow',
    'Tourney',
    'Trade Winds',
    'Train One',
    'Trirong',
    'Trispace',
    'Trocchi',
    'Trochut',
    'Truculenta',
    'Trykker',
    'Tulpen One',
    'Turret Road',
    'Ubuntu',
    'Ubuntu Condensed',
    'Ubuntu Mono',
    'Uchen',
    'Ultra',
    'Uncial Antiqua',
    'Underdog',
    'Unica One',
    'UnifrakturCook',
    'UnifrakturMaguntia',
    'Unkempt',
    'Unlock',
    'Unna',
    'Urbanist',
    'VT323',
    'Vampiro One',
    'Varela',
    'Varela Round',
    'Varta',
    'Vast Shadow',
    'Vesper Libre',
    'Viaoda Libre',
    'Vibes',
    'Vibur',
    'Vidaloka',
    'Viga',
    'Voces',
    'Volkhov',
    'Vollkorn',
    'Vollkorn SC',
    'Voltaire',
    'Waiting for the Sunrise',
    'Wallpoet',
    'Walter Turncoat',
    'Warnes',
    'Wellfleet',
    'Wendy One',
    'WindSong',
    'Wire One',
    'Work Sans',
    'Xanh Mono',
    'Yaldevi',
    'Yanone Kaffeesatz',
    'Yantramanav',
    'Yatra One',
    'Yellowtail',
    'Yeon Sung',
    'Yeseva One',
    'Yesteryear',
    'Yomogi',
    'Yrsa',
    'Yusei Magic',
    'ZCOOL KuaiLe',
    'ZCOOL QingKe HuangYou',
    'ZCOOL XiaoWei',
    'Zen Antique',
    'Zen Antique Soft',
    'Zen Dots',
    'Zen Kaku Gothic Antique',
    'Zen Kaku Gothic New',
    'Zen Kurenaido',
    'Zen Loop',
    'Zen Maru Gothic',
    'Zen Old Mincho',
    'Zen Tokyo Zoo',
    'Zeyada',
    'Zhi Mang Xing',
    'Zilla Slab',
    'Zilla Slab Highlight',
];

export const aBeeZee = ABeeZee({
    subsets: ['latin'],
    variable: '--font-abeezee',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const abel = Abel({
    subsets: ['latin'],
    variable: '--font-abel',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const abhayaLibre = Abhaya_Libre({
    subsets: ['latin'],
    variable: '--font-abhaya-libre',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const abrilFatface = Abril_Fatface({
    subsets: ['latin'],
    variable: '--font-abril-fatface',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const aclonica = Aclonica({
    subsets: ['latin'],
    variable: '--font-aclonica',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const acme = Acme({
    subsets: ['latin'],
    variable: '--font-acme',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const actor = Actor({
    subsets: ['latin'],
    variable: '--font-actor',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const adamina = Adamina({
    subsets: ['latin'],
    variable: '--font-adamina',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const adventPro = Advent_Pro({
    subsets: ['latin'],
    variable: '--font-advent-pro',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const aguafinaScript = Aguafina_Script({
    subsets: ['latin'],
    variable: '--font-aguafina-script',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const akayaKanadaka = Akaya_Kanadaka({
    subsets: ['latin'],
    variable: '--font-akaya-kanadaka',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const akayaTelivigala = Akaya_Telivigala({
    subsets: ['latin'],
    variable: '--font-akaya-telivigala',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const akronim = Akronim({
    subsets: ['latin'],
    variable: '--font-akronim',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const aladin = Aladin({
    subsets: ['latin'],
    variable: '--font-aladin',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alata = Alata({
    subsets: ['latin'],
    variable: '--font-alata',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alatsi = Alatsi({
    subsets: ['latin'],
    variable: '--font-alatsi',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const aldrich = Aldrich({
    subsets: ['latin'],
    variable: '--font-aldrich',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alef = Alef({
    subsets: ['latin'],
    variable: '--font-alef',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

// write the export of the next 10 fonts

export const alegreya = Alegreya({
    subsets: ['latin'],
    variable: '--font-alegreya',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alegreyaSC = Alegreya_SC({
    subsets: ['latin'],
    variable: '--font-alegreya-sc',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alegreyaSans = Alegreya_Sans({
    subsets: ['latin'],
    variable: '--font-alegreya-sans',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alegreyaSansSC = Alegreya_Sans_SC({
    subsets: ['latin'],
    variable: '--font-alegreya-sans-sc',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const aleo = Aleo({
    subsets: ['latin'],
    variable: '--font-aleo',
    display: 'auto',
    weight: ['400'],
    preload: false,
});

export const alexBrush = Alex_Brush({
    subsets: ['latin'],
    variable: '--font-alex-brush',
    display: 'auto',
    weight: ['400'],
    preload: false,
});
